import 'package:powersync/powersync.dart';

/// PowerSync schema definition - mirrors the PostgreSQL tables in Supabase.
/// PowerSync manages the local SQLite database and syncs with the remote DB.
const schema = Schema([
  Table('profiles', [
    Column.text('first_name'),
    Column.text('last_name'),
    Column.text('email'),
    Column.text('organization_id'),
    Column.text('role'),
    Column.text('signature_url'),
    Column.text('phone'),
    Column.integer('is_active'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('timesheet_entries', [
    Column.text('user_id'),
    Column.text('day_date'),
    Column.text('day_of_week'),
    Column.text('start_morning'),
    Column.text('end_morning'),
    Column.text('start_afternoon'),
    Column.text('end_afternoon'),
    Column.text('absence_reason'),
    Column.text('period'),
    Column.integer('has_overtime_hours'),
    Column.integer('is_weekend_day'),
    Column.integer('is_weekend_overtime_enabled'),
    Column.text('overtime_type'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('absences', [
    Column.text('user_id'),
    Column.text('timesheet_entry_id'),
    Column.text('start_date'),
    Column.text('end_date'),
    Column.text('type'),
    Column.text('motif'),
    Column.text('created_at'),
  ]),
  Table('anomalies', [
    Column.text('user_id'),
    Column.text('timesheet_entry_id'),
    Column.text('detected_date'),
    Column.text('description'),
    Column.integer('is_resolved'),
    Column.text('type'),
    Column.text('created_at'),
  ]),
  Table('overtime_configurations', [
    Column.text('user_id'),
    Column.integer('weekend_overtime_enabled'),
    Column.text('weekend_days'),
    Column.real('weekend_overtime_rate'),
    Column.real('weekday_overtime_rate'),
    Column.integer('daily_work_threshold_minutes'),
    Column.text('description'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('expenses', [
    Column.text('user_id'),
    Column.text('date'),
    Column.text('category'),
    Column.text('description'),
    Column.text('currency'),
    Column.real('amount'),
    Column.real('mileage_rate'),
    Column.integer('distance_km'),
    Column.text('departure_location'),
    Column.text('arrival_location'),
    Column.text('attachment_url'),
    Column.integer('is_approved'),
    Column.text('approved_by'),
    Column.text('manager_comment'),
    Column.text('approved_at'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('validation_requests', [
    Column.text('employee_id'),
    Column.text('manager_id'),
    Column.text('period_start'),
    Column.text('period_end'),
    Column.text('status'),
    Column.text('pdf_url'),
    Column.text('employee_signature_url'),
    Column.text('manager_signature_url'),
    Column.text('manager_comment'),
    Column.text('validated_at'),
    Column.text('expires_at'),
    Column.text('signing_step'),
    Column.text('client_signer_name'),
    Column.text('client_signer_email'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('notifications', [
    Column.text('user_id'),
    Column.text('type'),
    Column.text('title'),
    Column.text('message'),
    Column.text('data'),
    Column.integer('is_read'),
    Column.text('read_at'),
    Column.text('created_at'),
  ]),
  Table('generated_pdfs', [
    Column.text('user_id'),
    Column.text('file_name'),
    Column.text('file_url'),
    Column.text('generated_date'),
    Column.integer('month'),
    Column.integer('year'),
  ]),
  Table('manager_employees', [
    Column.text('manager_id'),
    Column.text('employee_id'),
    Column.text('created_at'),
  ]),
  Table('organizations', [
    Column.text('name'),
    Column.text('slug'),
    Column.text('parent_id'),
    Column.integer('is_active'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
]);
