// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZVukS9Hbwe4_6ztvzfjwPgr55mb5KgMc',
    appId: '1:209339291527:web:ddcb3b8fbaf39b730ae522',
    messagingSenderId: '209339291527',
    projectId: 'time-sheet-b86f6',
    authDomain: 'time-sheet-b86f6.firebaseapp.com',
    storageBucket: 'time-sheet-b86f6.firebasestorage.app',
    measurementId: 'G-VSKFB3X34L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5-uvSdPRP5SN85-oceYyb5hrhSUyWbWM',
    appId: '1:209339291527:android:2cb8de466562d2cc0ae522',
    messagingSenderId: '209339291527',
    projectId: 'time-sheet-b86f6',
    storageBucket: 'time-sheet-b86f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMHXOUBbrpZrPZ8IZlpkVE3bXG4nwk7RI',
    appId: '1:209339291527:ios:edbad80cd44294710ae522',
    messagingSenderId: '209339291527',
    projectId: 'time-sheet-b86f6',
    storageBucket: 'time-sheet-b86f6.firebasestorage.app',
    iosBundleId: 'com.jonathanlemaine.timeSheet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMHXOUBbrpZrPZ8IZlpkVE3bXG4nwk7RI',
    appId: '1:209339291527:ios:bfbf8e1e81775d7c0ae522',
    messagingSenderId: '209339291527',
    projectId: 'time-sheet-b86f6',
    storageBucket: 'time-sheet-b86f6.firebasestorage.app',
    iosBundleId: 'com.example.timeSheet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZVukS9Hbwe4_6ztvzfjwPgr55mb5KgMc',
    appId: '1:209339291527:web:b5058dc4131399290ae522',
    messagingSenderId: '209339291527',
    projectId: 'time-sheet-b86f6',
    authDomain: 'time-sheet-b86f6.firebaseapp.com',
    storageBucket: 'time-sheet-b86f6.firebasestorage.app',
    measurementId: 'G-0LGWLZXF73',
  );
}
