// Mocks generated by Mockito 5.4.4 from annotations
// in time_sheet/test/integration/weekend_validation_workflow_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:time_sheet/features/validation/domain/entities/validation_overtime_summary.dart'
    as _i5;
import 'package:time_sheet/features/validation/domain/entities/validation_request.dart'
    as _i4;
import 'package:time_sheet/features/validation/domain/services/validation_notification_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ValidationNotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockValidationNotificationService extends _i1.Mock
    implements _i2.ValidationNotificationService {
  MockValidationNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> notifyExceptionalWeekendHours({
    required _i4.ValidationRequest? validation,
    required _i5.ValidationOvertimeSummary? overtimeSummary,
    required String? managerName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #notifyExceptionalWeekendHours,
          [],
          {
            #validation: validation,
            #overtimeSummary: overtimeSummary,
            #managerName: managerName,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> notifyValidationApproved({
    required _i4.ValidationRequest? validation,
    required _i5.ValidationOvertimeSummary? overtimeSummary,
    required String? managerName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #notifyValidationApproved,
          [],
          {
            #validation: validation,
            #overtimeSummary: overtimeSummary,
            #managerName: managerName,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
