// Mocks generated by Mockito 5.4.4 from annotations
// in time_sheet/test/unified_overtime_calculator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:time_sheet/features/preference/presentation/widgets/overtime_calculation_mode_widget.dart'
    as _i4;
import 'package:time_sheet/services/overtime_calculation_mode_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [OvertimeCalculationModeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOvertimeCalculationModeService extends _i1.Mock
    implements _i2.OvertimeCalculationModeService {
  MockOvertimeCalculationModeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.OvertimeCalculationMode> getCurrentMode() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentMode,
          [],
        ),
        returnValue: _i3.Future<_i4.OvertimeCalculationMode>.value(
            _i4.OvertimeCalculationMode.monthlyWithCompensation),
      ) as _i3.Future<_i4.OvertimeCalculationMode>);

  @override
  _i3.Future<void> setCalculationMode(_i4.OvertimeCalculationMode? mode) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCalculationMode,
          [mode],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> isMonthlyCompensationEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isMonthlyCompensationEnabled,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> resetToDefault() => (super.noSuchMethod(
        Invocation.method(
          #resetToDefault,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
