name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 31.220.80.133
        username: root
        key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
        script: |
          cd /root/avasad-sheet/time_sheet_backend/time_sheet_backend_server
          
          # Pull les derniers changements (si c'est un repo git)
          # git pull origin main || echo "Not a git repo"
          
          # Redémarrer juste le backend avec les nouveaux fichiers
          docker restart timesheet-backend
          
          # Attendre que le backend redémarre
          sleep 5
          
          # Vérifier que tout fonctionne
          curl -I https://api-timesheet.wefamily.ch/ && echo "✅ API works!" || echo "❌ API down"
          
          docker ps --format "table {{.Names}}\t{{.Status}}"