name: Deploy to Contabo VPS

on:
  push:
    branches: [ main, production ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST || '31.220.80.133' }}
        username: ${{ secrets.VPS_USER || 'root' }}
        key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
        script: |
          cd /root/avasad-sheet/time_sheet_backend/time_sheet_backend_server
          
          # Variables
          DB_PASSWORD="${{ secrets.DB_PASSWORD || 'D3fPoHe2kANkIBLhARsxX3XyqtzZVS7g' }}"
          REDIS_PASSWORD="${{ secrets.REDIS_PASSWORD || '_C0f52i_lp0gETHNnCMs4iIK1BfeKy-W' }}"
          
          # Create config
          mkdir -p config
          cat > config/passwords.yaml << EOF
          production:
            database: '$DB_PASSWORD'
            redis: '$REDIS_PASSWORD'
          EOF
          
          # Use existing docker-compose
          if [ -f docker-compose.production.yml ]; then
            COMPOSE="docker-compose.production.yml"
          elif [ -f docker-compose.yaml ]; then
            COMPOSE="docker-compose.yaml"
          else
            COMPOSE="docker-compose.yml"
          fi
          
          # Build and deploy
          docker compose -f $COMPOSE build
          docker compose -f $COMPOSE up -d
          
          # Migrations
          for sql in migrations/*/migration.sql; do
            [ -f "$sql" ] && cat "$sql" | docker exec -i -e PGPASSWORD="$DB_PASSWORD" timesheet-postgres psql -U postgres -d time_sheet_backend || true
          done
          
          docker ps